# Generated by Django 6.0 on 2025-12-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('moyenne_min', models.FloatField()),
                ('moyenne_max', models.FloatField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, '1er'), (2, '2e'), (3, '3e')])),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.composante')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.eleve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.trimestre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField()),
                ('total_max', models.FloatField()),
                ('moyenne_sur_10', models.FloatField()),
                ('rang', models.PositiveIntegerField()),
                ('observation', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE_ENSEIGNANT', 'Validé enseignant'), ('VALIDE_DIRECTEUR', 'Validé directeur'), ('PUBLIE', 'Publié')], max_length=20)),
                ('appreciation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.appreciation')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.eleve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.trimestre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
