# Generated by Django 6.0 on 2025-12-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_eleve_options_and_more'),
        ('core', '0002_alter_anneescolaire_unique_together_and_more'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
    ]
