# Generated by Django 6.0 on 2026-01-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_composante_type_alter_bareme_unique_together'),
        ('core', '0003_delete_anneescolaire'),
        ('evaluations', '0002_alter_appreciation_tenant_alter_bulletin_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('tenant', 'eleve', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('tenant', 'eleve', 'composante', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('tenant', 'annee', 'numero')},
        ),
    ]
