# Generated by Django 6.0.1 on 2026-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_bulletin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='moyenne_sur_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='total_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='total_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
