# Generated by Django 6.0.1 on 2026-02-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_anneescolaire'),
        ('evaluations', '0004_alter_bulletin_moyenne_sur_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='date_generation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='rang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE_ENSEIGNANT', 'Validé par l’enseignant'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
