# Generated by Django 6.0.1 on 2026-02-03 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_anneescolaire'),
        ('evaluations', '0005_bulletin_date_generation_alter_bulletin_observation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE_ENSEIGNANT', 'Validé par l’enseignant'), ('VALIDE_DIRECTEUR', 'Validé par le directeur'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=30),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDE_ENSEIGNANT', 'Validation enseignant'), ('VALIDE_DIRECTEUR', 'Validation directeur'), ('PUBLIE', 'Publication')], max_length=30)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='evaluations.bulletin')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_action'],
            },
        ),
    ]
