# Generated by Django 6.0.1 on 2026-02-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_bareme_unique_together_bareme_matiere_and_more'),
        ('core', '0003_delete_anneescolaire'),
        ('evaluations', '0006_alter_bulletin_statut_validation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.composante'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('composante__isnull', False)), fields=('tenant', 'eleve', 'composante', 'trimestre'), name='uniq_note_par_composante'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere__isnull', False)), fields=('tenant', 'eleve', 'matiere', 'trimestre'), name='uniq_note_directe'),
        ),
    ]
