# Generated by Django 6.0.1 on 2026-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_note_unique_together_note_matiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='details_matiere',
            field=models.JSONField(blank=True, help_text='Détails figés par matière au moment de la publication', null=True),
        ),
    ]
