# Generated by Django 6.0.1 on 2026-02-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_bulletin_details_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='details_matiere',
        ),
    ]
