# Generated by Django 6.0.1 on 2026-03-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_remove_affectationenseignant_unique_affectation_enseignant_and_more'),
        ('evaluations', '0009_remove_bulletin_details_matiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trimestre',
            options={'ordering': ['annee', 'numero']},
        ),
        migrations.AddField(
            model_name='trimestre',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='cloture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='numero',
            field=models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2e trimestre'), (3, '3e trimestre')]),
        ),
    ]
