# Generated by Django 6.0.1 on 2026-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_alter_trimestre_options_trimestre_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='decision_conseil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
