# Generated by Django 6.0.1 on 2026-04-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message'),
        ('evaluations', '0011_bulletin_decision_conseil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PASSE', 'Passe en classe supérieure'), ('RESERVE', 'Passage avec réserve'), ('REDOUBLE', 'Redoublement'), ('EXAMEN', 'Présente examen'), ('NON_EXAMEN', 'Non présenté à l’examen'), ('ORIENTATION', 'Orientation spécifique')], max_length=20)),
                ('mention', models.CharField(blank=True, choices=[('FELICITATIONS', 'Félicitations'), ('ENCOURAGEMENTS', 'Encouragements'), ('AVERTISSEMENT', 'Avertissement')], max_length=20, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('autorise_examen', models.BooleanField(default=False)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='evaluations.bulletin')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
    ]
