# Generated by Django 6.0.1 on 2026-04-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_decisionconseil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='decision_conseil',
        ),
    ]
