# Generated by Django 6.0.1 on 2026-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_remove_bulletin_decision_conseil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionconseil',
            name='decision',
            field=models.CharField(choices=[('PASSE_EN_CLASSE_SUPERIEURE', 'Passe en classe supérieure'), ('RESERVE', 'Passage avec réserve'), ('REDOUBLE', 'Redoublement'), ('EXAMEN', 'Présente examen'), ('NON_EXAMEN', 'Non présenté à l’examen'), ('ORIENTATION', 'Orientation spécifique')], max_length=30),
        ),
    ]
