# Generated by Django 6.0.1 on 2026-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_alter_decisionconseil_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
