# Generated by Django 6.0 on 2025-12-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='anneescolaire',
            name='tenant',
        ),
    ]
