# Generated by Django 6.0 on 2025-12-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_eleve_options_and_more'),
        ('core', '0002_alter_anneescolaire_unique_together_and_more'),
        ('evaluations', '0002_alter_appreciation_tenant_alter_bulletin_tenant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnneeScolaire',
        ),
    ]
