# Generated by Django 6.0.1 on 2026-03-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_anneescolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'École publique'), ('PRIVE', 'École privée')], default='PUBLIC', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='academie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academie'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('departement', models.CharField(max_length=100)),
                ('academie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.academie')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inspection'),
        ),
    ]
