# Generated by Django 6.0.1 on 2026-03-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_region_departement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom']},
        ),
    ]
