# Generated by Django 6.0.1 on 2026-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='signature_directeur',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
