# Generated by Django 6.0.1 on 2026-03-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0015_classe_niveau_systeme_eleve_ine'),
        ('core', '0004_academie_tenant_type_tenant_academie_inspection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.FloatField(default=0)),
                ('taux_reussite', models.FloatField(default=0)),
                ('effectif_total', models.IntegerField(default=0)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('academie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.academie')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire')),
            ],
            options={
                'unique_together': {('academie', 'annee')},
            },
        ),
    ]
