# Generated by Django 6.0.1 on 2026-02-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_eleve_parent'),
        ('accounts', '0002_parent'),
        ('core', '0003_delete_anneescolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='eleves',
            field=models.ManyToManyField(blank=True, related_name='parents', to='academics.eleve'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
