# Generated by Django 6.0.1 on 2026-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parent_eleves_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_SAAS', 'Administrateur SaaS'), ('ADMIN_TENANT', 'Administrateur Établissement'), ('ADMIN_NATIONAL', 'Administrateur National'), ('ADMIN_IEF', "Administrateur de l'IEF"), ('ADMIN_ACADEMIE', "Administrateur de l'Académie"), ('DIRECTEUR', 'Directeur'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent')], max_length=20),
        ),
    ]
