# Generated by Django 6.0.1 on 2026-03-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cni_user_telephone_alter_user_tenant'),
        ('core', '0004_academie_tenant_type_tenant_academie_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
