# Generated by Django 6.0.1 on 2026-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
