# Generated by Django 6.0.1 on 2026-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_cni_alter_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
