# Generated by Django 6.0 on 2025-12-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='effectif',
            new_name='effectif_prevu',
        ),
        migrations.AlterUniqueTogether(
            name='eleve',
            unique_together={('tenant', 'matricule')},
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.CharField(default='CE2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='nom',
            field=models.CharField(default='CE2 A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='composante',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=9)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('tenant', 'libelle')},
            },
        ),
        migrations.AlterField(
            model_name='bareme',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.anneescolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('tenant', 'annee', 'nom')},
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='libelle',
        ),
    ]
