# Generated by Django 6.0 on 2026-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_eleve_options_and_more'),
        ('core', '0003_delete_anneescolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='composante',
            name='type',
            field=models.CharField(choices=[('RESSOURCE', 'Ressource'), ('COMPETENCE', 'Compétence')], default='INCONNU', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bareme',
            unique_together={('tenant', 'composante', 'classe', 'annee')},
        ),
    ]
