# Generated by Django 6.0 on 2026-02-02 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_affectationclasse'),
        ('core', '0003_delete_anneescolaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.matiere')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('enseignant', 'classe', 'matiere', 'annee', 'tenant')},
            },
        ),
    ]
