# Generated by Django 6.0 on 2026-02-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_affectationenseignant'),
        ('core', '0003_delete_anneescolaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationclasse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='affectationclasse',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='affectationclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_enseignants', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='affectationclasse',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affectationclasse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationclasse',
            unique_together={('enseignant', 'classe', 'annee', 'tenant')},
        ),
    ]
