# Generated by Django 6.0.1 on 2026-02-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_affectationclasse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composante',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
