# Generated by Django 6.0.1 on 2026-02-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_matiere_type_evaluation_alter_matiere_tenant'),
        ('core', '0003_delete_anneescolaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bareme',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bareme',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.matiere'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.composante'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
