# Generated by Django 6.0.1 on 2026-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_bareme_unique_together_bareme_matiere_and_more'),
        ('core', '0003_delete_anneescolaire'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bareme',
            constraint=models.UniqueConstraint(condition=models.Q(('composante__isnull', False)), fields=('tenant', 'classe', 'annee', 'composante'), name='uniq_bareme_par_composante'),
        ),
        migrations.AddConstraint(
            model_name='bareme',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere__isnull', False)), fields=('tenant', 'classe', 'annee', 'matiere'), name='uniq_bareme_par_matiere'),
        ),
    ]
