# Generated by Django 6.0.1 on 2026-02-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_bareme_uniq_bareme_par_composante_and_more'),
        ('accounts', '0002_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='accounts.parent'),
        ),
    ]
