# Generated by Django 6.0.1 on 2026-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_eleve_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='parent',
        ),
    ]
