# Generated by Django 6.0.1 on 2026-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_populate_inscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='niveau_systeme',
            field=models.CharField(choices=[('ELEMENTAIRE', 'Élémentaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], default='ELEMENTAIRE', max_length=20),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ine',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
