# Generated by Django 6.0.1 on 2026-03-29 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_classe_niveau_systeme_eleve_ine'),
        ('core', '0004_academie_tenant_type_tenant_academie_inspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationenseignant',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='affectationenseignant',
            index=models.Index(fields=['enseignant', 'classe', 'tenant'], name='idx_affectation_enseignant_classe_tenant'),
        ),
        migrations.AddIndex(
            model_name='affectationenseignant',
            index=models.Index(fields=['matiere', 'classe', 'tenant'], name='idx_affectation_matiere_classe_tenant'),
        ),
        migrations.AddConstraint(
            model_name='affectationenseignant',
            constraint=models.UniqueConstraint(fields=('enseignant', 'classe', 'matiere', 'annee', 'tenant'), name='unique_affectation_enseignant'),
        ),
    ]
