# Generated by Django 6.0.1 on 2026-03-29 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_affectationenseignant_unique_together_and_more'),
        ('core', '0004_academie_tenant_type_tenant_academie_inspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affectationenseignant',
            name='unique_affectation_enseignant',
        ),
        migrations.RenameIndex(
            model_name='affectationenseignant',
            new_name='idx_affect_ens_cls_tnt',
            old_name='idx_affectation_enseignant_classe_tenant',
        ),
        migrations.RenameIndex(
            model_name='affectationenseignant',
            new_name='idx_affect_mat_cls_tnt',
            old_name='idx_affectation_matiere_classe_tenant',
        ),
        migrations.AddConstraint(
            model_name='affectationenseignant',
            constraint=models.UniqueConstraint(fields=('enseignant', 'classe', 'matiere', 'annee', 'tenant'), name='uniq_affect_ens'),
        ),
    ]
