# Generated by Django 6.0.1 on 2026-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_remove_affectationenseignant_unique_affectation_enseignant_and_more'),
        ('core', '0004_academie_tenant_type_tenant_academie_inspection_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['tenant', 'annee'], name='academics_i_tenant__49f83a_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['eleve', 'actif'], name='academics_i_eleve_i_4b08ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('eleve',), name='unique_active_inscription_per_eleve'),
        ),
    ]
