# Generated by Django 6.0.1 on 2026-03-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_inscription_academics_i_tenant__49f83a_idx_and_more'),
        ('core', '0005_region_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='core.departement'),
        ),
    ]
