# Generated by Django 6.0.1 on 2026-03-31 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_eleve_departement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['-date_inscription']},
        ),
    ]
