# Generated by Django 6.0.1 on 2026-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_inscription_options'),
        ('core', '0007_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscription',
            name='unique_active_inscription_per_eleve',
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('eleve', 'annee'), name='unique_active_inscription_per_eleve'),
        ),
    ]
