# Generated by Django 6.0.1 on 2026-04-10 15:28

import academics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_remove_inscription_unique_active_inscription_per_eleve_and_more'),
        ('accounts', '0011_user_signature'),
        ('core', '0008_tenant_signature_directeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('fichier', models.FileField(upload_to=academics.models.upload_path)),
                ('type_document', models.CharField(choices=[('ACTE', 'Acte de naissance'), ('CERTIFICAT', 'Certificat médical'), ('PHOTO', 'Photo identité'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.parent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_upload'],
                'indexes': [models.Index(fields=['tenant'], name='academics_d_tenant__78a57d_idx'), models.Index(fields=['eleve'], name='academics_d_eleve_i_9e1940_idx'), models.Index(fields=['parent'], name='academics_d_parent__6f065b_idx')],
            },
        ),
    ]
