# Generated by Django 6.0.1 on 2026-04-29 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'tenant_id'], name='notificatio_user_id_fbb02a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event'], name='notificatio_event_i_1afed9_idx'),
        ),
    ]
